# Generated by Django 4.2.9 on 2024-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last_name')),
                ('number', models.CharField(max_length=15, verbose_name='number')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='photo')),
            ],
        ),
    ]
